import nodemailer from 'nodemailer';
import { SITE_BRAND, CONTACT_EMAIL } from '@/lib/brand';
import { siteOrigin } from '@/lib/site-origin';

interface EmailConfig {
  host: string;
  port: number;
  secure: boolean;
  auth: {
    user: string;
    pass: string;
  };
}

interface ContactEmailData {
  name: string;
  email: string;
  subject: string;
  message: string;
}

// Create email transporter
const createTransporter = () => {
  const config: EmailConfig = {
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false, // true for 465, false for other ports
    auth: {
      user: process.env.SMTP_USER || '',
      pass: process.env.SMTP_PASSWORD || '',
    },
  };

  return nodemailer.createTransport(config);
};

// Send contact form email
export const sendContactEmail = async (data: ContactEmailData): Promise<void> => {
  const transporter = createTransporter();
  
  const mailOptions = {
    from: process.env.SMTP_FROM || 'whoppromocodes@gmail.com',
    to: 'whoppromocodes@gmail.com',
    subject: `New enquiry via contact form: ${data.subject}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #333; border-bottom: 2px solid #6366f1; padding-bottom: 10px;">
          New message received from your contact form
        </h2>
        
        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #6366f1; margin-top: 0;">Sender details</h3>
          <p><strong>Name:</strong> ${data.name}</p>
          <p><strong>Email:</strong> ${data.email}</p>
          <p><strong>Subject:</strong> ${data.subject}</p>
        </div>
        
        <div style="background-color: #ffffff; padding: 20px; border: 1px solid #e9ecef; border-radius: 8px;">
          <h3 style="color: #6366f1; margin-top: 0;">Message content</h3>
          <p style="white-space: pre-wrap; line-height: 1.6;">${data.message}</p>
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e9ecef; color: #666; font-size: 12px;">
          <p>This notification was generated by the ${SITE_BRAND} contact form.</p>
          <p>You can reply directly to reach ${data.name} at ${data.email}.</p>
        </div>
      </div>
    `,
    replyTo: data.email,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log('Contact email sent successfully');
  } catch (error) {
    console.error('Error sending contact email:', error);
    throw new Error('Failed to send email');
  }
};

// Send auto-reply email to the user
export const sendAutoReply = async (data: ContactEmailData): Promise<void> => {
  const transporter = createTransporter();
  const origin = siteOrigin();

  const mailOptions = {
    from: process.env.SMTP_FROM || CONTACT_EMAIL,
    to: data.email,
    subject: `We've received your message – thank you for getting in touch`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 10px;">
          Thanks for reaching out to ${SITE_BRAND}
        </h2>

        <p>Hi ${data.name},</p>

        <p>Thanks for getting in touch. We've received your message and will respond as soon as we can.</p>
        
        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #6366f1; margin-top: 0;">Summary of your message</h3>
          <p><strong>Subject:</strong> ${data.subject}</p>
          <p><strong>Message:</strong></p>
          <p style="white-space: pre-wrap; line-height: 1.6; font-style: italic;">${data.message}</p>
        </div>
        
        <div style="background-color: #e0e7ff; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #6366f1; margin-top: 0;">What happens next</h3>
          <ul style="line-height: 1.6;">
            <li>Someone from our team will review your message shortly</li>
            <li>We'll reply directly to you at ${data.email}</li>
            <li>If something is time-sensitive, including "URGENT" in the subject line helps us spot it faster</li>
          </ul>
        </div>
        
        <p>In the meantime, you can browse our latest digital deals at <a href="${origin}" style="color: #6366f1;">${SITE_BRAND}</a>.</p>

        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e9ecef; color: #666; font-size: 12px;">
          <p>Kind regards,<br>The ${SITE_BRAND} team</p>
          <p>Visit the site: <a href="${origin}" style="color: #6366f1;">${origin}</a></p>
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log('Auto-reply email sent successfully');
  } catch (error) {
    console.error('Error sending auto-reply email:', error);
    // Don't throw here as auto-reply is not critical
  }
};

// Test email configuration
export const testEmailConfig = async (): Promise<boolean> => {
  try {
    const transporter = createTransporter();
    await transporter.verify();
    console.log('Email configuration is valid');
    return true;
  } catch (error) {
    console.error('Email configuration test failed:', error);
    return false;
  }
};