/**
 * CLEAN SITEMAP GENERATOR
 *
 * Generates these files:
 * - public/sitemap-offers.xml (exactly 121 /offer/<slug> URLs in launch mode)
 * - public/sitemap-static.xml (hardcoded allowlist of static routes)
 * - public/sitemap-blog.xml (published blog posts)
 * - public/sitemap.xml (index referencing the above)
 *
 * NO noindex sitemap.
 * NO legacy /whop/ routes.
 * NO chunked sitemaps.
 * NO dynamic discovery of static routes.
 *
 * This is the CANONICAL sitemap generation script for whoppromocodes.com launch.
 */

import { PrismaClient } from '@prisma/client';
import { writeFileSync, rmSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';

const prisma = new PrismaClient();

// === CONFIGURATION ===
const SITE_URL = 'https://whoppromocodes.com';
const EXPECTED_COHORT_COUNT = 1451;

// === STATIC ROUTES ALLOWLIST ===
// These are the ONLY static routes that will be included in the sitemap.
// NO BLOG. NO /whop/. NO dynamically discovered routes.
// NOTE: /offers is intentionally EXCLUDED - noindex hub during launch phase.
// Revisit in 4-6 weeks once individual pages have authority.
const STATIC_ROUTES = [
  { path: '/', priority: 1.0, changefreq: 'daily' },
  { path: '/about', priority: 0.7, changefreq: 'monthly' },
  // /offers excluded - noindex hub page, revisit post-launch
  { path: '/privacy', priority: 0.5, changefreq: 'yearly' },
  { path: '/terms', priority: 0.5, changefreq: 'yearly' },
  { path: '/contact', priority: 0.6, changefreq: 'monthly' },
  { path: '/submit', priority: 0.7, changefreq: 'monthly' },
  { path: '/how-to-redeem', priority: 0.6, changefreq: 'monthly' },
];

// === COHORT SLUGS (121 curated offers) ===
// Source: data/launch-cohort-curated-101.json + top-100-rewritten-content.json (first 20)
const LAUNCH_COHORT_SLUGS = [
  '-silver-tier-fyndit',
  '4orte-tiktok-upgrade',
  'ace-of-trades-',
  'ai-news-bot',
  'alertsify',
  'american-dream-mentorship',
  'amnotify-japan-renewal',
  'anonymous-sport-bets',
  'ascent-repricer',
  'beat-the-books',
  'bet-bettor-weekly',
  'betmagic-pro-membership',
  'blastoises-premium',
  'boka-trading-premium',
  'boosted-betz-premium',
  'bullish-bandits',
  'chart-hackers-pay-with-crypto',
  'chroma-trading',
  'coliseeprivateclub-premium',
  'creator-cartel',
  'crypto-archie-vip',
  'datawise-sports-betting',
  'deal-soldier',
  'divine-premium-access',
  'doc-prop-gold',
  'dodgys-dungeon',
  'ecom-tools-pro',
  'edu-elite-30-platinum',
  'elevate-community',
  'empire-sports',
  'enrich-trades-blueprint',
  'flash-fund-premium',
  'flipalert-membership-usa',
  'freecash-premium',
  'frugal-season',
  'full-port-university-annual',
  'gg33-enlightened-academy',
  'glo-sports-chat',
  'goat-sports-bets-membership',
  'grindlife-plays',
  'heatseeker-access',
  'hidden-society-trading',
  'hobbyist-collective-membership',
  'hold-my-hand-wholesale-pass',
  'house-of-resell',
  'house-of-stimms-vip',
  'jdub-trades-premium',
  'larrys-lounge-premium',
  'limitless-rei-wholesale',
  'lowkey-discord-membership',
  'lunch-money-membership',
  'market-fluidity-university',
  'mc-sports-premium',
  'media-metas',
  'meme-mafia',
  'miles-high-club-crypto-pay',
  'mogul-stock-group-premium',
  'momentum-monthly',
  'moon-trades-lifetime',
  'ndotdiab-vip-access',
  'new-age-trading-premium',
  'nextwave-indicators',
  'ofm-empire-vip-full-access',
  'owls-full-access',
  'parlay-minds-premium',
  'parlayscience-discord-access',
  'peloswing-premium-access',
  'pj-trades-premium',
  'pokefinder',
  'polar-chefs-premium',
  'potion-discord-access-crypto',
  'potion-tracker-whale',
  'profit-pioneers',
  'propbet-mafia',
  'propfellas-vip',
  'resale-radar-discord',
  'resellers-paradise-premium',
  'scalboost-club',
  'scarface-trades-premium',
  'sharpmoney-all-access-vip',
  'shocked-crypto-payments',
  'skyridge-toolbox',
  'sourced-betting-bots',
  'stellar-aio',
  'stock-talk-insiders',
  'tailored-trades-premium',
  'the-haven',
  'the-options-cartel-full-access',
  'the-sweepers-vip',
  'the-yard-dropship-mastermind',
  'ticket-broker-u-pro',
  'titans-algo-pro',
  'tms-1-on-whop',
  'tms-heavy-hitters-',
  'trade-with-insight-pro',
  'unity-academy-membership',
  'vulture',
  'wealth-group-crypto-pay',
  'your-first-dollar',
  'zth-player-accelerator',
  'zzz-money-club-vip',
  // === EXPANDED BATCH (45 slugs) - High-Value Rewritten Content ===
  // Updated: 2026-01-13
  // Note: 5 slugs deleted from Whop (korvato-gold-rush, metatradingai, alliance-group-coaching, growthopia-fz-llc, liv-cam-paid)
  'airbnb-empire-builder',
  'm1-capital-accelerator',
  'the-8-figure-masterclass',
  'daniel-g-hubzome-lda-speaking',
  'minotaur-consulting-services',
  'omnifunds',
  'million-dollar-brand-club',
  'global-wealth-mentorship',
  'asgard-bootcamp',
  'youtube-consulting',
  'lifetime-diamond-package-',
  '200k-500k-challenge',
  'lux-nomads-essentials',
  'innova-trade-ai',
  'devvy',
  // === NEW ADDITIONS (30 slugs) - 2026-01-13 ===
  'sober-living-riches',
  'optinsio',
  'fes-bootcamp',
  'the-only-system-you-need',
  'jlu-637',
  'platinum-tier-fast-action',
  'real-business-solutions',
  'royalty-hero-elite',
  'elite-coaching-academy',
  'arbitrage-society',
  'ttw-inner-circle',
  'daniel-g-x-d2d-con',
  'daniel-g-x-alkaline-electric',
  'capital-funding-accelerator',
  'skillset-solutions',
  'springboard-to-wealth',
  'riverz-marketing',
  'wall-street-academy',
  'leadconsulting-ai',
  'tms-spartan-ai-bot',
  'great-energy-capital',
  'just-funded',
  'acquisition-network-',
  'agency-partner-package',
  'wholesale-to-millions',
  'the-trading-apprentice',
  'career-evolved',
  'lux-nomads-vip',
  // === EDITORIAL REVIEWS BATCH (42 slugs) - 2026-01-16 ===
  'the-godspeed-growth-system',
  'section-8-cartel',
  'affiniti-flow',
  'swayer',
  'listing-agent-accelerator',
  'airflow',
  'sovereign-man',
  'momentum-circle',
  'fernpicks-diamond-package',
  'qa-automation-job-interviews',
  'tech-sales-job-interviews',
  'osa-gold-program',
  'the-ai-incubator',
  'acquisition-ace',
  'learn-minerals',
  'locatelli-acquisition',
  'data-engineer-academy-fin',
  'baller-package',
  'the-high-ticket-ecom-program',
  'electrin-group',
  'consulting-utopia-dfy',
  'fit-n-healthy',
  'ai-profit-lab',
  'formula-6',
  'ayecon-academy-lifetime-membership',
  'mdbc-tiktok-hop',
  'amazon-inner-circle',
  'the-real-sales-academy',
  'digital-creator-university',
  'gold-tier',
  'exclusive-calls',
  'beyond-clinical-care',
  'info-scaler',
  'diagofit',
  'goodlife-brand-accelerator',
  'accelerator-program',
  'inovate',
  'learn-airbnb-arbitrage',
  'sickboytrades-mentorship',
  'the-black-room',
  'tiktok-shop-accelerator',
  '7th-level-community',
  // === EDITORIAL REVIEWS BATCH 2 (67 slugs) - 2026-01-19 ===
  '1-on-1-coaching',
  '1of1locks',
  '360-sales-agency',
  '4everpaidbets',
  'accs-bot-vinted',
  'ai-for-pros',
  'aj-trading',
  'alex-crypto-universe',
  'alminmilanovic',
  'amazon-aco',
  'betwithhaddy',
  'bullprooftrading-strategy',
  'bullstocks',
  'businessgrowr-aaf-dfy-setup',
  'capital-44-elite-group',
  'cc-compass',
  'cdr-premium-betting',
  'chaos-indicator-for-trading',
  'cisero-ai',
  'coaching-by-brian',
  'creativeforge',
  'credit-repair-balance-2nd-pay',
  'criscklukks-whop',
  'dcoptions',
  'ddu-online-services-agency-4',
  'degen-vip',
  'delux',
  'dialos-major-league-profits',
  'diontrades',
  'dm-setting',
  'domsprops',
  'dubai-plug',
  'earnit-media',
  'essentials-to-trading',
  'falco-queue-buster',
  'flipflip-membership-og',
  'flipseek',
  'flxpickz-premium',
  'forked-creatives',
  'founders-arm',
  'freedom-team-mentorship',
  'freedomers',
  'future-founders-club',
  'game-changer-premium',
  'ghost-inner-circle',
  'glitchybets',
  'high-ticket-incubator',
  'hooksquare-contractors',
  'iced-investments-subscription',
  'infoprosio',
  'institutional-trading',
  'intensevalue',
  'inventory-insiders',
  'jlgrowth',
  'juiced-bets-vip-discord',
  'locks-together-premium',
  'master-your-money',
  'opusmagna-trading',
  'resistance',
  'saas-university',
  'steal-my-agency',
  'tennisxpert-premium',
  'the-locksmiths-hq',
  'traders-accelerator',
  'uncle-shaundys-trading-den',
  'zeus-bets',
  'zoom-trading-vip',
  // === EDITORIAL REVIEWS BATCH 3 (9 slugs) - 2026-01-22 ===
  'resell-radar',
  'tradialy',
  'pikes-peak-trades-advantage',
  'wave-maestro',
  'remote-riches',
  'opc-all-plays',
  'sigmavue',
  'exotic-fleet-formula',
  'canary-chain',
  // === PROMO CODE BATCH 1 (100 slugs) - 2026-01-29 ===
  'speed-ramp-from-a-to-z',
  '1-month-premium',
  '1-of-1-traders-full-access',
  '1-month-access-vipparlay-king',
  '1-on-1-mentorship-lifetime',
  '100-creative',
  '10kto50k-challenge-elite-plan',
  '1',
  '3-days-free-luxury-picks',
  '3-leaf-clover',
  '333picks',
  '3m-trading-vip-group-access',
  '4-leaf-clover',
  '6-figure-wash-system',
  '60-day-ab-strength-for-golfers',
  'itsbucketsnba-vip-telegram',
  'a-z-trading-guide-',
  'aa-trading',
  'ad-plus',
  'adt-diamond-lifetime',
  'adt-vip-gold-complete',
  'aementorship-basic-mentorship',
  'ai-fusion-megapack',
  'ai-signals-premium',
  'alive-trades-alliance-ata',
  'am-elites-premium',
  'amzshifu-university',
  'ape-trading',
  'apex-fitness-and-mind-mastery',
  'ar-trades',
  'archetype-premium',
  'atm-picks-pass',
  'abhey-takes-down-vegas-free',
  'acesso-alpha',
  'advanced-english-community',
  'agency-blueprint',
  'agency-domain',
  'algo28-day-trading-signals',
  'algobot-premium',
  'algorithmic-trading-blueprint',
  'all-access',
  'all-access-vip',
  'all-in-one-indicator-package',
  'alpha-market-pro',
  'amazon-fba-mastery',
  'amazon-fba-success-network',
  'american-dream-trading-crypto',
  'american-dream-trading-futures',
  'american-dream-trading-premium',
  'angelo-props-bread-winners',
  'anonymous-traders',
  'arbitrage-alley-pro',
  'ashleydoubles-community',
  'attention-economy-club',
  'aura-picks-vip',
  'aura-picks-vip-pass',
  'ayecon-academy-monthly-mentorship',
  'bankroll-bros-weekly',
  'bfx-signals',
  'blw-master-app',
  'ballerpicks-vip',
  'baseline-bets',
  'basic-plan',
  'basic-trading-mentorship',
  'beamly-hyper-growth',
  'best-of-both-worlds',
  'bet-sports-daily',
  'betdubs-premium',
  'betropolis-vip-esports-bot',
  'betting-central-101',
  'bettorprocess-member',
  'big-tick-energy-premium',
  'bigjoebets',
  'bigplaynate-monthly-gl',
  'blackhawk-indicator',
  'blackwolftrading',
  'blastoises-lifetime-premium',
  'blitzersports-vip',
  'blockchain-bureau-apprentice',
  'bobbys-bets-sports-analytics',
  'bookie-breakers-vip',
  'boominati-io-membership',
  'bors-trading-premium',
  'brand-leverage-blueprint',
  'brand-partnership-blueprint',
  'braver-crypto-vip',
  'bronze-package',
  'build-your-brand-ecom-coaching',
  'build-your-first-app-with-ai',
  'bulhaven-trading-group',
  'bullfrogs-investment-community',
  'caa-itin-forensic-training',
  'ccs-collectibles',
  'ceo-trades-lifetime-access',
  'clean-sweeps-vip',
  'cms-basic-ta-course',
  'cms-vip',
  'cryptowzrd',
  'cali-betz',
  'caps-7-day-package',
  // === PROMO CODE BATCH 2 (100 slugs) - 2026-02-01 ===
  'caps-monthly-package',
  'capital-complex-premium',
  'cash-it-betting-vip',
  'catalyst-culture-membership',
  'cellzier',
  'certified-crypto-pro',
  'champagne-trades-premium',
  'champions-sports-bets-premium',
  'charts-membership',
  'cipher-sol',
  'clippers-flow-premium',
  'clippie-ai-lite',
  'clipping-cartel',
  'clube-de-membros-vip',
  'codycoverspreads-vip',
  'collectables-reselling',
  'cookinfos-exclusive-resell',
  'cookin-crew',
  'copy-paste-digital-creator',
  'copytraders-worst-copytraders',
  'creator-blueprint',
  'credit-elevation-program',
  'crown-crypto-premium',
  'crypto-crusaders-premium',
  'crypto-hungary-market-maker',
  'crypto-rich-vip',
  'crypto-wolf-pack',
  'cryptopro',
  'cryptohub-premium-trading',
  'currency-creators-vip',
  'cyber-study-group',
  'cyptics-alpha',
  'dleyguarda-trading',
  'daily-straight-plays',
  'db-locks',
  'dms-picks',
  'dots-trading-bias-indicator',
  'dsplocks-premium',
  'dt',
  'dtr-trading',
  'dxb-crypto-investors-club',
  'daily-pips-premium-access',
  'dan-steel-trading-academy',
  'darius-fx-inner-circle',
  'data-trader-premium',
  'dawah-central',
  'defi-mojo',
  'dead-longer-than-alive',
  'dealking',
  'decus-private',
  'depop-method-community',
  'desarrollo-exponencial',
  'digital-vault',
  'digital-wealth-simplified',
  'discord-algo-combo',
  'discord-alerts',
  'doctorate-',
  'dodgys-ultimate-course',
  'dojo-deals',
  'donalds-store',
  'dres-playbook',
  'dreamsbets-vip',
  'drop-oclock-membership',
  'drysdale-trading-group',
  'dynamo-vip',
  'edge-pro-beliebt-',
  'era-mastery',
  'espn-bens-sportcenter',
  'etu-100rr-advanced-course',
  'etu-private-journal-access',
  'ez-algo',
  'ez-bulls-trading',
  'easy-ways-to-bet',
  'eczema-healing-community',
  'education-trading-group',
  'elite-access-pro',
  'elite-coaches-community',
  'elite-premium',
  'elite-squad-network',
  'elite-syndicate-bets',
  'elite-vip-membership',
  'elitetradingsnipers-20',
  'envelope-business-deposit',
  'envxys-kingdom',
  'equifix',
  'esprit-boursier-accs-discord',
  'euphoric-trading-elite',
  'euphoric-trading-vip',
  'exclusive-live-bet-chat',
  'executive-chef',
  'fba-accelerator-course',
  'fba-lead-scraper',
  'fc-trading-lab',
  'franklin-covers',
  'fte-model',
  'ftg-trading',
  'fvg-mindful-trading-pro',
  'fx-telepath-diamond-membership',
  'fxd-academy',
  'fast-track-20-course',
  // === PROMO CODE BATCH 3 (100 slugs) - 2026-02-02 ===
  'fifteenmin-premium',
  'film-insider',
  'financing-funnel-formula',
  'finupwise-de',
  'first-class-discord',
  'fit-girl-workouts-program',
  'flex-fx-vip-signals',
  'flipflip-og-membership',
  'flipping-to-freedom',
  'flipping-to-freedom-full-offer',
  'flipping-to-freedom-lego',
  'follow-the-leader',
  'forex-kurs-funded-werden',
  'framework',
  'freedom-fundamentals',
  'friends-family',
  'full-coaching-community',
  'fundinglab-vip-signals',
  'funko-corps-monthly',
  'future-finance-elite',
  'fxpremiere-fx-signals',
  'geno-elite',
  'goat-picks-vip',
  'gold-signals-xauusd-vip',
  'golden-goat-trading',
  'gtg-vip',
  'gtrader-master-prop-trading',
  'gala-trades-premium',
  'galaxia-etu',
  'gamblers-paradise-prem',
  'gemini-trading-indicator',
  'gencorp-trading',
  'gentle-capital',
  'geraldine-trades',
  'global-trade-empire-vip',
  'gnotz-algo-on-tradingview',
  'goat-ecom-growth',
  'goatedkel-picks',
  'god-backdoor-membership',
  'gold-plan',
  'goodfellas-sports-discord',
  'got-lockz',
  'green-team-trading',
  'greens-jackpot-player-props',
  'grizzly-trades',
  'guitar-mastery',
  'gurus-film-room',
  'h1-to-m5-model',
  'hopium',
  'hsv-consulting',
  'hack-academy',
  'haikhuu-trading-gold',
  'hall-of-fame-fund',
  'hammer-investments-guarantee',
  'hammer-investments-monthly',
  'heatpicks',
  'hermes-sneaker-reselling',
  'honeycomb-options-trading',
  'house-cat',
  'house-money-club',
  'house-of-mambas',
  'hybrid-whales-premium',
  'hypernova-membership',
  'i-am-trading-standard',
  'iblv-live',
  'iblv-trading-vip-discord',
  'infra-trade-telegram-alerts',
  'iwb-course-discord',
  'icelocks-premium',
  'ignited-tools',
  'immo-elite',
  'indelible-patrons',
  'indicators-vip-lifetime',
  'influencer-university-',
  'inner-circle-academy',
  'inner-circle-amazon-platinum',
  'internet-money-trading',
  'internet-money-trading-mt5',
  'ivolution-trading',
  'jc-locks',
  'jarvis-alerts',
  'jaypickzem',
  'jomos-trades',
  'jokers-hideout',
  'josh-exclusive-vip-access',
  'journal-with-the-holy-spirit',
  'justpips-trading',
  'kenny-trades',
  'king-68-picks',
  'king-analytics-381',
  'kingdom-business-ventures',
  'kingdom-kounseling',
  'kiwee-trades-paid-access',
  'kodas-prop-picks',
  'kryptoknowledge-alpha',
  'ku2z-king',
  'kurlyfries-vip-access',
  'kvfx-algo-indicator',
  'k-signals-premium',
  'lanotify-in-store-membership',
  // === PROMO CODE BATCH 4 (100 slugs) - 2026-02-03 ===
  'live-trading-gold-monthly',
  'lka-vinted-snipe-bot',
  'labstrike',
  'labubu-drops-vip-membership',
  'lade-backk-algo-indicator',
  'lade-backk-trading-discord',
  'learn-how-to-trade-with-me',
  'learn-with-ibrahim',
  'learningcrypto-premium',
  'leeke-picks-membership',
  'legup-picks',
  'legendaryparlay-discord',
  'legerity-trading-membership',
  'lets-begin-community',
  'lets-get-this-money',
  'leverage-university',
  'life-rpg',
  'lifetime-premium-membership',
  'lifetime-vip',
  'limitless-ai-sport-picks',
  'line-snipers-membership',
  'linebreaker-picks',
  'linkedin-client-lab',
  'live-trading-sessions-m-f',
  'locked-in-trading',
  'locking-profits-premium',
  'lordsports-baseball',
  'lotto-parlays-player-props',
  'lucid-capital-monthly',
  'lucky-arbitrage-premium',
  'lune-auto-trader',
  'lune-trading-premium',
  'lune-trading-pro',
  'mental-picks-amazon-ebay',
  'meta-brand-scaling',
  'mirror-tradinglifetime',
  'monthly-straight-plays-elite',
  'msu-kb-bets-discord',
  'mtm-vip-discord',
  'mac-money-family',
  'madmoney-trading',
  'magic-lines-premium',
  'major-wagers',
  'make-millions-clipping',
  'mambafitcoach',
  'mango-pools-subscription',
  'market-masters-trading',
  'marketing-party-central',
  'master-the-bull-seminar',
  'mastering-market-mentorship',
  'max-maserati-model-pro',
  'max-maserati-model-20-elite',
  'maxalgo-traders-toolkit',
  'maxs-premium-access',
  'media-metas-clips',
  'membership-card-payments',
  'membership-crypto-payments',
  'membresia-boletos',
  'membresa-clsica-zero',
  'memecoin-mastery',
  'merkabah-13',
  'mikkjo-trading-vip',
  'militia-mentor',
  'millionaire-memecoins',
  'millionaire-premier-club-mpc',
  'millionaire-traders-alliance',
  'millionaires-metaforum-live',
  'mind-gains-memecoin-mastery',
  'mind-of-khan-free-community',
  'mindful-af-attentionfocus',
  'minted-monthly-access',
  'minted-yearly-access-crypto',
  'minteddao-monthly-crypto-pay',
  'mobile-money-university',
  'moementum-university',
  'mogul-builder',
  'moms-house',
  'momentum-blueprint',
  'money-momentum',
  'monitorius-vinted-bot-1',
  'monthly-elites-itm',
  'monthly-member-of-mmm',
  'monthly-plan',
  'monthly-premium-membership',
  'monthly-signals',
  'moon-trades-monthly',
  'mr-wicks-discord',
  'mysportpick',
  'nbl-community-access',
  'nfx-academy-vip',
  'novahittas',
  'nycalert-pass',
  'netbetz',
  'never-doubt',
  'new-trader-boot-camp-0625',
  'new-years-sale',
  'nexus-ai-trades',
  'nickspicks-premium',
  'nickspicks-premium-monthly',
  'nighteye-agency',
  // === PROMO CODE BATCH 5 (100 slugs) - 2026-02-04 ===
  'nova-select-analytics',
  'novo-legacy-trading-vip',
  'occam-trading-group',
  'od-pilna-naryst',
  'ofm-empire-trends-vip',
  'ofm-empire-vip-marketplace',
  'ofm-penthouse-vip-access',
  'on-brand',
  'otc-group',
  'oceanaio-exclusive',
  'ogs-private',
  'one-trade-system',
  'only-the-punchers',
  'operator-labs',
  'option-insights-discord',
  'options-action',
  'options-premium-group',
  'options-pro-club',
  'oracle-insights-qt-indicator',
  'originationmodeling',
  'overman-group',
  'owls-options-traders-twitter',
  'own-your-damn-power-ai-studio',
  'palm-fx-copytrader',
  'pbg-consultation-silver',
  'pingted-mois-super',
  'paidofflock-premium',
  'paidinfull-program-full',
  'papapickz-money-making',
  'papecheck-picks-community',
  'papecheck-picks-premium',
  'pariahbets',
  'paris-young-academy',
  'parlay-pros',
  'parlayxpapi-props',
  'parlizzypapi-vip-gold',
  'payout-palace-picks',
  'peakflow',
  'pennies-2-prosperity',
  'penny-stock-mafia',
  'pham-collectibles-pokalerts',
  'phantom-picks',
  'phantom-trading',
  'phantombets-premium',
  'pick-pray-vip-',
  'pick-city-monthly',
  'pick-city-weekly',
  'picxys-premium',
  'pine-script-pro-trader',
  'pipclub-savage-ea-forex-robot',
  'platinum-access',
  'platinum-vip-ai-sports-picks',
  'player-props',
  'player-props-vip',
  'plugged-inn-weekly-access',
  'potion-discord-access',
  'potion-tracker-advanced',
  'potion-tracker-starter',
  'power-picks',
  'powerhomes-tools-pro',
  'premium-weekly-membership',
  'premium-access-monthly',
  'premium-discord-monthly',
  'premium-discord-weekly',
  'premium-live-trading',
  'premium-membership-',
  'premium-pinterest',
  'premium-plan',
  'premium-subscription',
  'premium-trader',
  'prestige',
  'primepicks-premium-free-trial',
  'primepicks-premium-membership',
  'print-money-w-tiktok',
  'print-money-w-tiktok-course',
  'printsquad-fnp-trades',
  'pro-membership',
  'pro-trader',
  'prodigy',
  'prodigy-picks-access',
  'product-pushers-lifetime',
  'profit-house-trading-group',
  'profit-python',
  'profit-society-inc',
  'profitbeasts-sports-bets',
  'providencefx-coaching-lab',
  'pure-trading-ventures',
  'queezy-locks-904',
  'quantsignals',
  'quantumresearch-systems',
  'rr-lounge',
  'rb-picks-premium',
  'rja-accelerator-eur',
  'rl-labs-premium',
  'royalty-trading-group',
  'rybets-premium-group',
  'rainbowalgo-monthly-access',
  'rapidtickets-pro',
  'relicusroad-pro-bundle',
  'resell-kings',
  // === PROMO CODE BATCH 6 (100 slugs) - 2026-02-05 ===
  'resell-signals-premium-group',
  'reselling-accelerator',
  'reverse-split-snipers',
  'rich-off-risk',
  'rich-wtg',
  'ricocapital-member',
  'riley-picks',
  'road-2-revenue',
  'road-to-millions-vip',
  'royal-british',
  'ryan-wagner-sports-vip-plays',
  'salvobets',
  'sanjaleo-trading',
  'satorifnf',
  'sbt-20-off',
  'scf-diamond',
  'scousepicks-premium',
  'seller-central-boys-',
  'sems-premium-server',
  'sf-essential',
  'sf-ultimate',
  'shark-action-group-og',
  'sharp-edge-premium',
  'sharp-picks',
  'sharp-slips-all-access',
  'sharpmoney-ev-main-markets',
  'sharpmoney-ev-player-props',
  'sharpshooters-sports-picks',
  'shisha-traders-club',
  'shortkingbets-vip',
  'side-hustle-collection',
  'signal-room-bundle',
  'signal-vault',
  'silver-spoon-bets',
  'sistema-instruccional',
  'skell-nation-all-access',
  'skyline-deluxe-',
  'slam-dunk-bets',
  'smart-money-concepts-course',
  'smart-money-vip',
  'sneaker-cookgroup',
  'snttrades-nur-videokurs',
  'soccer-picks-master-vip-club',
  'soccer-slips-premium',
  'social-circle-start-creating',
  'social-university',
  'sovo-network',
  'spoofer-pro',
  'sports-betting-theory',
  'sports-picks',
  'sportsplayz-premium',
  'stellar-aio-3rd-instance',
  'storyradar',
  'str8-bets',
  'straight-plays-elite',
  'strategy-school',
  'stratoholics-anonymous',
  'streaming-mentorship',
  'stridetrades',
  'study-of-chart',
  'stupid-simple-devs',
  'subscription-with-card',
  'summit-academy-inner-circle',
  'supercar-income',
  'supercar-income-broker',
  'supply-drop-monitors-premium',
  'sureedge-bets',
  'sushi-fnf-access-options',
  'swush-trading-premium',
  'system-based-betting',
  'tail-it-vip',
  'tby-investments',
  'tcgtracker',
  'team-alpha-daily-text-alerts',
  'telesales-premium',
  'th-picks',
  'the-ai-space',
  'the-ape-asylum',
  'the-art-of-financing',
  'the-bfi-traders-university',
  'the-bible-of-aesthetics',
  'the-bikini-model-diet',
  'the-crypto-collective-premium',
  'the-currency-merchant-vip',
  'the-delta-vader-copy-tader',
  'the-den-indicator-suite',
  'the-dojo',
  'the-early-byrd',
  'the-financial-cloud-combo',
  'the-financial-cloud-indicators',
  'the-floor-signals-chat',
  'thg-algo-system',
  'tiktok-wiz-premium-product',
  'title-iv-d-university',
  'tlr-distribution',
  'tmmb-premium',
  'tms-exclusive-vip-chat',
  'tms-player-props-',
  'tsa-clothing-only',
  'tss-access',
  // === PROMO CODE BATCH 7 (131 slugs) - 2026-02-06 ===
  'the-hangar',
  'the-haven-pay-with-crypto',
  'the-hundredx-club',
  'the-interstellar',
  'the-interstellar-2',
  'the-kyan-method',
  'the-liquidity-vault',
  'the-lock-talk-long-term',
  'the-mastermind',
  'the-mosh-pick',
  'the-outlet-premium',
  'the-parlay-pros',
  'the-profit-playbook',
  'the-shein-ambassador-program',
  'the-trade-syndicate',
  'the-traders-club',
  'the-trading-shelter-premium-v2',
  'the-trading-syndicate',
  'the-trenches-premium',
  'the-vault-discord',
  'the-wizards-brew',
  'thefacelessformula',
  'thezaxis-membership',
  'thooth-pings',
  'thumbnail-academy-',
  'ticketvision-trading',
  'tier-2-team-member',
  'tiktok-affiliate-foundation',
  'time-before-price',
  'timeline',
  'tipsonpips',
  'tonafba-wholesale-program',
  'top-tier-vip-access',
  'trade-bandit-elite',
  'trade-buddy-indicators',
  'trade-copy-service-only',
  'trade-with-solo',
  'tradelabs-ultimate-trading-bot',
  'trademark-support',
  'trader-capital-premium',
  'traders-roadmap-premium',
  'traderade-premium-service',
  'traders-pathway-discord-access',
  'trading-accelerator-premium',
  'trading-levels-algo-basic',
  'trading-levels-algo-standard',
  'trading-louis-full-course',
  'trading-louis-live-stream',
  'trading-louis-stream-chat',
  'training-with-tiah',
  'trench-hunters',
  'trend-fusion-algo-with-discord',
  'trendvision-subscription',
  'triad-24',
  'triple-7-parlays',
  'university-membership',
  'us30-indicator',
  'ultimate-tweaks',
  'umbrella-vip-picks',
  'under450ks-private-community',
  'unlockable-character',
  'value-lock-sports-ultimate-vip',
  'vinted-plug-abonnement-goat',
  'vip',
  'vip-1-month',
  'vip-3-months',
  'vip-club-membership-tier',
  'vip-download-spoofer-bot',
  'vip-money-millionaires',
  'vip-monthly',
  'vip-discord-access',
  'vipparlay-king',
  'vegas-ninja-premium',
  'vegas-shark-premium-picks-',
  'velaris-trading-de',
  'velaris-trading-premium',
  'vinted-snipe-bot',
  'vip-access-package',
  'vipweek',
  'viperrs-premium',
  'viralcash',
  'virality',
  'vito-commercis-free-community',
  'vito-foundations',
  'volaris-learn-how-to-use-ai',
  'whnsa-roi',
  'wva-advanced-coaching-program',
  'wager-wire',
  'wagerhub-premium',
  'wall-street-jd',
  'waynes-pivots-pro',
  'webtrend-most-popular',
  'weekly-clutch-membership',
  'weekly-cooks',
  'whales-r-us-premium',
  'wi-fi-route-club',
  'win-the-day-monthly',
  'win-with-alex-discord-vip',
  'win-the-day-vip',
  'winners-posse-pass',
  'x-levels-pro-tradex',
  'x1-alpha-group',
  'xauusd-signals-monthly',
  'xtyphoon',
  'xenith-trading-membership',
  'yutaka-alpha',
  'z1-capital-membership',
  'zulabs-academy',
  'zwm-gold',
  'zwm-lifetime-access',
  'zapify-amazon-oawholesale',
  'zeddy-lockz-monthly-premium',
  'zeiierman-all-inclusive',
  'zeiierman-trading-signals',
  'zen-trading-premium',
  'zenith-trading',
  'zeus-trades-apprenticeship',
  'fulfilledby-group-a2a-bots',
  'httpscercleppmfr',
  'otc-bot',
  'lite-pro-',
  '-cometleads-tier-1-shuffled',
  '-elite-plan',
  'crypto-capital-vip',
  'parlaycapital-premium',
  'taxes-are-voluntary-w-oto',
  '-basic-access',
  '-the-ofm-incubator-',
  'bullish-premium-chat',
  'rfb-exclusivevip-package',
  'solo-vintedseekers',
  // 2026-03-03 — Single addition
  'team2trading-private-access',
  // 2026-03-06 — New offer additions (49 slugs)
  'social-army-jerry',
  'wealth-group-credit-card-ig',
  'wealth-group-credit-card-pay',
  'heatseekers-membership',
  'heatseeker-glitch-algo',
  'kingcapsports-full-access',
  'trophies-discord-access',
  'courtside-locks',
  'stock-levels-university',
  '-bravo-six-picks-vip',
  '-bravo-six-picks-lifetime',
  'exclusive-analytics-vip-bundle',
  'adrevival-bronze',
  'adrevival-diamond',
  'adrevival-gold',
  'adrevival-platinum',
  'adrevival-tiktok',
  'crystal-academy-membership',
  'ybb-sports-data',
  'pb-alerts-premium',
  'pb-trading-premium',
  'pb-crypto-membership',
  'kc-trades-mastermind',
  'kc-trades-premium-discord',
  'eztrades-pro-access',
  'american-dream-trading-vip',
  'american-dream-vip-lifetime',
  'adt-futures-vip',
  'cook-the-books-vip-access',
  'options-insider-pro',
  'options-insider-lifetime',
  'options-insider-key-levels',
  'raketrades-premium',
  'full-port-university-vip',
  'full-port-university-challenge',
  'traveling-trader-premium',
  'the-traveling-trader-lifetime',
  'traveling-trader-year-upgrade',
  'rising-phoenix-trading',
  'luxurytools',
  'bettor-odds-all-access',
  'bettor-odds-ev',
  'bettor-odds-predictions',
  'bh-insights',
  'bh-insights-crypto-payment',
  'cheeselocks',
  'the-market-lens',
  'impact-investments',
  'uncharted-vip-access',
  // 2026-03-18 — New offer additions (10 slugs)
  'black-tie-analytics',
  'ghostsportzpickz',
  'hidden-aio',
  'hobbyhangout-discord',
  'pokecop',
  'shiny-town',
  'toolsuite-vip',
  'trade-pro-elite',
  'tuscanyrose',
  'spy-essentials',
  // 2026-03-18 — Existing DB offers now live (69 slugs)
  'tjr-advanced-indicators',
  'deal-flip-formula-main',
  'ecomtalent',
  'viral-flow',
  'gfnf-bets-pass',
  'medialabs-germany',
  'team-bull-monthly',
  'betrecaps-vip-discord',
  'stock-hours-algo-membership',
  'honey-drip-network-live',
  'viral-vision',
  '247-cash-flow-university-vip',
  'swipesignals-renewal',
  'official-picks-free-access',
  'fu-money-club-access',
  'flipfluence',
  'bandars-bounties-member-pass',
  'pokenotify-trainer-pass',
  'equinox-premium',
  'value-spy-crew-basic',
  'bookie-bandit',
  'traffic-hackers-lite',
  'her-last-call-academy',
  'rise-now-premium',
  'the-buy-box-membership',
  'sindbad-ki-kryptoanalyse',
  'commercive-membership',
  'book-of-alpha-premium',
  'live-academy',
  'the-sartorial-trading-mastery',
  'elite-options-pro',
  'ecom-paradise-mentorship',
  'only-bands-money-group',
  'rippy-club',
  '1of1dfs-sports',
  'tailed-enterprize',
  'poke-signals',
  'oasis-mastermind',
  '50x-club',
  'dcrypt-premium',
  'tickio-eu-membership',
  'sniper-trades-basic',
  'aurora-trading-premium',
  'creators-syndicate',
  'peachy-investor-school',
  'zeto-picks-1-month',
  'futdreamss-premium',
  'content-academy-30',
  'degen-tavern-standard-access',
  'demontrading-vip-member',
  'the-top-floor-mentorship',
  'school-of-gods-members',
  'adextrades-memorial-day-sale',
  'paragn-elite-membership',
  'desperado-sales-group',
  'topblast',
  'the-locker-room',
  'trade-with-titans',
  'dr-profits-trading-university',
  'promoguy-plus',
  'social-club-academy',
  'arbitrage-ops-premium',
  'yaupicks-membership',
  'trade-crypto-by-design-vip',
  'bread-and-butter-pass',
  'membership-1-month',
  'apprentice',
  'student',
  'rios-to-riches',
  // 2026-03-18 — Final 5 new offers
  'ecom-degree-university',
  'frugal-season-black-box',
  'spy-bank',
  'sousa-vip-room',
  'powertrades-membership',
  // 2026-04-09 — Top earner additions (96 slugs)
  'big-gains-club-premium',
  'toptierbetz-academy',
  'risingphoenixtrades',
  'whale-room',
  'bet-labs-discord-premium',
  'aba100x',
  'tikey-tickets-manager',
  'monetize-course-community',
  'kenan-grace',
  'trading-profit-path',
  'flex-futures',
  '247-terminal',
  'trade-craft-tools',
  'impact-team',
  'jonah-s-stocks-options-group',
  'trade-hub',
  'props-lab',
  'traders-compound',
  'sam-jak-llc',
  'printsquad',
  'stock-king-sharks',
  'the-goldmine',
  'spy-day-trading',
  'profit-insider',
  'unity-academy',
  'art-s-crypto-circle',
  'motion-members',
  'nextgen-publishers',
  '4orte',
  'firststeptrading',
  'gargantua-aio',
  'tookthattradinggroup',
  'freedom-builders',
  'edge-zone-core',
  'dopamine',
  'dealmama',
  'resell-locker',
  'vintrez',
  'bullish-empire',
  'daily-grind-trading',
  'vincere-aut-mori',
  'atm-picks',
  'league-mastery',
  'poke-alerts',
  'creatorflow-premium',
  'pokepings',
  'just-do-sales-academy',
  'earnelite',
  'on-socials',
  'levels-sports-picks',
  'lazy-alpha-society',
  'stealthpack',
  'crypto-crusaders',
  'matched-betting-empire',
  'the-trading-tutor',
  'traderzz',
  'the-wave-makers',
  'printor',
  'day-trading-institution',
  'day-trading-with-source',
  'sports-roulette',
  '1time-esports-plays',
  'zen-trading',
  'sweepflow',
  'tradewellx',
  'mza',
  'the-data-layers',
  'invest-with-matt',
  'alpha-system-accelerator',
  'order-flow-mastery',
  '6-figure-ofm',
  'stock-surfer-capital',
  'zed-trading-accelerator',
  'bluemoontrades-premium',
  'ecom-elite',
  'scaleflow',
  'the-labs',
  'turtle-ev-labs',
  'fortheculturefx-vip',
  'mabac-media',
  'medstra',
  'growthmind-ai',
  'the-capcut-system',
  'the-halal-hustle-club',
  'the-steak-team',
  'dad-dtc-affiliate-dominator',
  'inner-circle',
  'order-checker-bot',
  'jarvisflow',
  'wealth-capital',
  'numerology',
  'markets-unmasked',
  'tribuclaw',
  'zhu-trades',
  'jg-insurance-group-llc',
  'the-creative',
  // 2026-04-09 — Top earner activations + new records (158 slugs)
  'rt-picks-vip',
  'ecom-masterclass',
  'bet-bettor-sports-monthly',
  'gg33-silver',
  'link-up-community',
  'paragn-network',
  'top-floor-trading-discord',
  'divine-degen',
  'endurance-membership',
  'lions-den',
  'netzwerk-a-z-kursplattform',
  'premium-access',
  'goatify',
  'the-hustle-club-premium',
  'mtmverse-premium-stocks',
  'viral-pass',
  'dealhawk',
  'huracan-trading-akademia',
  'tempo-trades-premium',
  'diamond-tier-',
  'the-mail-room',
  'asozial-reich',
  'dispurgen-membership',
  'tts-insiders',
  'lv-trades-membership',
  'derivatives-trading',
  'startup-preneurs-premium',
  'baron-trades-premium',
  'savage-ecom-community',
  'paper-gains-monthly',
  'autoflipped',
  'facebook-listing-tool',
  'weekly-gold-member',
  'levs-locks-club-house',
  'gammaedge-premium',
  'house-of-profits-premium',
  'elite-premium-membership',
  'livecops-server',
  'playbook-investment-group',
  'de-wolf-van-washington',
  'pokefreeze-notify',
  'swift-algo-indicator',
  'tickets',
  'ig-growth-tool',
  '28-club-with-runitup',
  'all-in-premium',
  'exclusive-access-monthly',
  'cb-trading-investing-academy',
  'the-alliance',
  'shadows-chefs-vip',
  'the-ultimate-trading-arena',
  'socialbuz-tiktok-payday',
  'trading-ranch-vip',
  'trinity-trading-partners',
  'the-champagne-room',
  'zamunda-membership',
  'insiderz-membership',
  'deal-sniper',
  'paystowait',
  'chillimanpicks-vip',
  'exposcale-community',
  'the-family-membership',
  'black-sheep-culture-club',
  'premium-university',
  'nautilus-deals-membership',
  'price-hacking',
  'assassin-stocks-premium',
  'unknowncollect',
  'gabetrades',
  'notify-france-affiliate-',
  'monster-bet',
  'ourbologroup-membership',
  'solartools-solarmail',
  '502slips',
  'venomcooks-germany',
  'bta-premium',
  'megoda-membership',
  'moonboys-crypto',
  'ar-collective-membership',
  'pushing-profit',
  'vip-trading-network',
  '444-capital',
  'shadow-flips-premium',
  'cakes-bakes-membership',
  'dipbuymafia-vip-pro',
  'surging-cards',
  'highest-paid-nurse-community',
  'selfmade-society',
  'voss-trading-vip-monthly',
  'card-followers-membership',
  '242-just-picks',
  'straight-shooters',
  'nikeshoebot-nsb',
  'databasedbets-discord',
  'bali-project-bets',
  'gains-gears',
  'tiktok-ugc-ad-creator-course',
  'team-100k-trading-group',
  'gold-squad-vip',
  'walmart-101',
  'monthly-trading-access',
  'pay2playuniversity-course',
  'the-alpha-club-elite-group',
  'no-sweat-bets',
  'pilots-licence',
  'trading-options-academy-toa',
  'kinnobot-pro',
  'heems-picks',
  'cards',
  'lj-pickz-aus-nz',
  'the-sweatshop',
  'stock-paper-scissors',
  'average-hustlers-membership',
  'onlyscheduler-pro',
  'ascend-trading-premium',
  'sports-package',
  'off-the-board',
  'engage-diamond-user',
  'ticketwave-inner-circle',
  'tjr-indicators-bundle',
  'cheese-fran-ev',
  'ticketwave-lenstvo',
  'sleeved',
  'pickd-vip',
  'jeets-full-vip-',
  'brick-dynasty-app',
  'eliteclouds-vip-signals',
  'ecom-essentials',
  'elite-bricks-monthly',
  'open-trading-collective-elite',
  'prisma-trading-signals-elite',
  'trade-blueprint',
  'level-3-masterheart-circle',
  'tradolusion-pro',
  'the-shit-bot-tsb',
  'premium-discord',
  'smt-for-time-based-sessions',
  'gmp-discord-membership',
  'ur-hustle-house',
  'the-ryze-network',
  'bulls-corner-7-day-trial',
  'trade-the-unknown',
  'limitless',
  'trade-assist-premium',
  'the-lab-premium-membership',
  'platinum-trading-premium',
  'select-trading-discord',
  'the-syndicate',
  'thewave',
  'trade-manager-exclusive',
  'gambling-gurus-community',
  'edgebet-membership',
  'akari-tickets',
  'traders-blueprint',
  'e-commerce-builders',
  'creator-cashflow',
  'arcane-society',
  'creator5',
  // 2026-04-09 — Top earner activations from handoff (29 slugs)
  'viral-vision-a-z-tiktok-kurs',
  'exclusive-mastermind-members',
  'official-picks-premium',
  'alpine-premium-access',
  'clutch-investments-monthly',
  'full-package-exclusive-offer',
  'amnotify-us-membership',
  '-gold-tier-fyndit',
  'plugged-inn-premium-membership',
  'the-doc-prop-platinum',
  'tsa-trading-investing-only',
  'premium',
  'hidden-society-full-membership',
  'stock-hours-signals-chat',
  'honey-drip-option-trading',
  'cfu-full-membership',
  'shocked',
  'miles-high-club-card-pay',
  'bandars-bounties-membership',
  'private-mentorship',
  'the-agent-accelerator-program',
  'ecom-paradise-pro',
  'peachy-trading-school',
  'oasis-trading-vip',
  'sniper-trades-premium',
  'aurora-professional-zones',
  'chart-hackers',
  'promoguy-sportsbooks-ev',
  'kckd-premium-access',
  // 2026-04-13 — Clean names list activations (33 slugs)
  'potion-3-month-access',
  'ca-chefs-profit-lounge',
  'insider-sport-picks',
  'silently',
  'resellers-paradise-fba-premium',
  'bet-bettor-free-trial',
  'dr-profit-premium',
  'promoguy-all-inclusive',
  'ca-chefs-endurance',
  'certified-crypto-alpha',
  'npz-trading',
  'fully-monetized-yt-channel',
  'tiktok-money-maker-blueprint-m',
  'diamond-trading-vip',
  'printers-paradise',
  'lv-trades',
  'the-lab',
  'gammaedge-lite',
  'crypto-archie-big-bundle',
  'moneyboys-stock-premium',
  'boss-up-academy',
  'fba-academy-deposit',
  'self-made-society',
  'kinno-wealth',
  'onlyscheduler-x-onlyspoofer',
  'degentopro-sports-monthly',
  'ticketwave-albania',
  'grouped-solutions-lifetime',
  'dxb-crypto-investor-tier',
  'prisma-trading-signals',
  'crypto-freedom-academy-6',
  'auto-flip-academy',
  // 2026-04-14 — Final additions (new + dormant activations)
  'uproas',
  'qmm-indicators-academy',
  '247-research',
  'stocks-with-josh-swj-fam',
  'potion-tracker-pro',
  'stock-hours-vip-bundle',
  'all-in',
  'ecomessentials',
  'market-masters',
];

// === XML GENERATION HELPERS ===

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function generateUrlEntry(url: string, lastmod: string, changefreq: string, priority: number): string {
  return `  <url>
    <loc>${escapeXml(url)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

function wrapUrlset(entries: string[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</urlset>`;
}

function generateSitemapIndex(sitemaps: string[]): string {
  const now = new Date().toISOString();
  const entries = sitemaps.map(url => `  <sitemap>
    <loc>${escapeXml(url)}</loc>
    <lastmod>${now}</lastmod>
  </sitemap>`);

  return `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</sitemapindex>`;
}

// === ASSERTIONS ===

// Locale pattern to detect locale-prefixed paths (EN-only invariant)
const LOCALE_PATH_PATTERN = /\/(en|es|fr|de|it|pt|nl|zh|ja|ko|ru|ar)\//i;

function assertNoBadUrls(urls: string[], allowBlog = false): void {
  for (const url of urls) {
    if (url.includes('/whop/')) {
      throw new Error(`FATAL: URL contains /whop/: ${url}`);
    }
    if (!allowBlog && url.includes('/blog/')) {
      throw new Error(`FATAL: URL contains /blog/: ${url}`);
    }
    if (url.includes('?')) {
      throw new Error(`FATAL: URL contains query string: ${url}`);
    }
    if (url.endsWith('/') && url !== `${SITE_URL}/`) {
      throw new Error(`FATAL: URL has trailing slash: ${url}`);
    }
    // EN-only invariant: No locale prefixes in URLs
    if (LOCALE_PATH_PATTERN.test(url)) {
      throw new Error(`FATAL: URL contains locale prefix (EN-only mode): ${url}`);
    }
  }
}

function assertNoLegacyFiles(publicDir: string): void {
  // Files the script legitimately generates (whitelist)
  const allowedFiles = [
    'sitemap.xml',
    'sitemap-offers.xml',
    'sitemap-static.xml',
    'sitemap-blog.xml',
  ];

  // Exact filenames that should never exist
  const legacyExactFiles = [
    'sitemap-index.xml',
  ];

  // Prefixes - any file starting with these is legacy
  const legacyPrefixes = [
    'sitemap-whops',    // catches sitemap-whops-1.xml, sitemap-whops-2.xml, etc.
    'sitemap-noindex',  // catches sitemap-noindex.xml, sitemap-noindex-old.xml, etc.
    'sitemap-gone',     // catches any gone variants
  ];

  const files = existsSync(publicDir) ? readdirSync(publicDir) : [];

  for (const file of files) {
    // Only check sitemap files
    if (!file.startsWith('sitemap')) continue;

    // Skip files we legitimately generate
    if (allowedFiles.includes(file)) continue;

    // Check exact matches
    if (legacyExactFiles.includes(file)) {
      throw new Error(`FATAL: Legacy sitemap file found: ${file} - delete this file`);
    }

    // Check prefix matches
    for (const prefix of legacyPrefixes) {
      if (file.startsWith(prefix)) {
        throw new Error(`FATAL: Legacy sitemap file found: ${file} - delete this file`);
      }
    }
  }
}

// === MAIN ===

async function main() {
  console.log('🗺️  CLEAN SITEMAP GENERATOR');
  console.log('===========================\n');
  console.log(`Site URL: ${SITE_URL}`);
  console.log(`Expected cohort count: ${EXPECTED_COHORT_COUNT}\n`);

  const publicDir = join(process.cwd(), 'public');

  // Step 1: Clean up any legacy sitemap files first
  console.log('🧹 Cleaning up legacy sitemap artifacts...');

  // Remove public/sitemaps/ directory entirely
  const sitemapsDir = join(publicDir, 'sitemaps');
  if (existsSync(sitemapsDir)) {
    rmSync(sitemapsDir, { recursive: true });
    console.log('   Removed public/sitemaps/');
  }

  // Remove any legacy sitemap files from public/
  // Note: sitemap.xml, sitemap-static.xml, sitemap-offers.xml, sitemap-blog.xml
  // are NOT in this list because the script generates them fresh
  const legacyFiles = [
    'sitemap-index.xml',
    'sitemap-whops-1.xml',
  ];

  for (const file of legacyFiles) {
    const filepath = join(publicDir, file);
    if (existsSync(filepath)) {
      rmSync(filepath);
      console.log(`   Removed public/${file}`);
    }
  }

  console.log('');

  // Step 2: Validate cohort count
  console.log('📊 Validating cohort...');
  if (LAUNCH_COHORT_SLUGS.length !== EXPECTED_COHORT_COUNT) {
    throw new Error(`FATAL: Expected ${EXPECTED_COHORT_COUNT} slugs, got ${LAUNCH_COHORT_SLUGS.length}`);
  }
  console.log(`   ✅ Cohort has exactly ${EXPECTED_COHORT_COUNT} slugs\n`);

  // Step 3: Verify all cohort slugs exist in DB
  console.log('🔍 Verifying cohort slugs exist in database...');
  const dbDeals = await prisma.deal.findMany({
    where: {
      slug: { in: LAUNCH_COHORT_SLUGS },
      retired: false,
    },
    select: { slug: true, updatedAt: true, indexingStatus: true },
  });

  const dbSlugs = new Set(dbDeals.map(d => d.slug));
  const missingSlugs = LAUNCH_COHORT_SLUGS.filter(s => !dbSlugs.has(s));

  if (missingSlugs.length > 0) {
    console.error('   Missing from DB:', missingSlugs);
    throw new Error(`FATAL: ${missingSlugs.length} cohort slugs not found in database`);
  }
  console.log(`   ✅ All ${EXPECTED_COHORT_COUNT} slugs exist in database\n`);

  // Step 4: Generate offer sitemap
  console.log('📝 Generating sitemap-offers.xml...');
  const now = new Date().toISOString();

  // Sort by slug for determinism
  const sortedDeals = [...dbDeals].sort((a, b) => a.slug.localeCompare(b.slug));

  const offerUrls: string[] = [];
  const offerEntries: string[] = [];

  for (const deal of sortedDeals) {
    const url = `${SITE_URL}/offer/${deal.slug}`;
    offerUrls.push(url);
    offerEntries.push(generateUrlEntry(
      url,
      deal.updatedAt.toISOString(),
      'weekly',
      0.8
    ));
  }

  // Assert no bad URLs
  assertNoBadUrls(offerUrls);

  const offerSitemap = wrapUrlset(offerEntries);
  writeFileSync(join(publicDir, 'sitemap-offers.xml'), offerSitemap);
  console.log(`   ✅ Generated sitemap-offers.xml with ${offerEntries.length} URLs\n`);

  // Step 5: Generate static sitemap
  console.log('📝 Generating sitemap-static.xml...');

  const staticUrls: string[] = [];
  const staticEntries: string[] = [];

  for (const route of STATIC_ROUTES) {
    // Homepage needs trailing slash to match Google's crawled URL
    const url = route.path === '/' ? `${SITE_URL}/` : `${SITE_URL}${route.path}`;
    staticUrls.push(url);
    staticEntries.push(generateUrlEntry(
      url,
      now,
      route.changefreq,
      route.priority
    ));
  }

  // Assert no bad URLs
  assertNoBadUrls(staticUrls);

  const staticSitemap = wrapUrlset(staticEntries);
  writeFileSync(join(publicDir, 'sitemap-static.xml'), staticSitemap);
  console.log(`   ✅ Generated sitemap-static.xml with ${staticEntries.length} URLs\n`);

  // Step 6: Generate blog sitemap
  console.log('📝 Generating sitemap-blog.xml...');

  const publishedPosts = await prisma.blogPost.findMany({
    where: { published: true },
    select: { slug: true, updatedAt: true, publishedAt: true },
    orderBy: { publishedAt: 'desc' },
  });

  const blogUrls: string[] = [];
  const blogEntries: string[] = [];

  for (const post of publishedPosts) {
    const url = `${SITE_URL}/blog/${post.slug}`;
    blogUrls.push(url);
    blogEntries.push(generateUrlEntry(
      url,
      (post.updatedAt || post.publishedAt || new Date()).toISOString(),
      'monthly',
      0.7
    ));
  }

  // Assert no bad URLs (allow blog URLs for this sitemap)
  assertNoBadUrls(blogUrls, true);

  const blogSitemap = wrapUrlset(blogEntries);
  writeFileSync(join(publicDir, 'sitemap-blog.xml'), blogSitemap);
  console.log(`   ✅ Generated sitemap-blog.xml with ${blogEntries.length} URLs\n`);

  // Step 7: Generate sitemap index (as sitemap.xml for GSC compatibility)
  console.log('📝 Generating sitemap.xml (index)...');

  const sitemapList = [
    `${SITE_URL}/sitemap-offers.xml`,
    `${SITE_URL}/sitemap-static.xml`,
  ];

  // Only include blog sitemap if there are published posts
  if (blogEntries.length > 0) {
    sitemapList.push(`${SITE_URL}/sitemap-blog.xml`);
  }

  const sitemapIndex = generateSitemapIndex(sitemapList);

  writeFileSync(join(publicDir, 'sitemap.xml'), sitemapIndex);
  console.log(`   ✅ Generated sitemap.xml referencing ${sitemapList.length} sitemaps\n`);

  // Step 8: Final assertions
  console.log('🔒 Running final assertions...');
  assertNoLegacyFiles(publicDir);
  console.log('   ✅ No legacy sitemap files found\n');

  // Step 9: Summary
  console.log('═══════════════════════════════════════');
  console.log('✅ CLEAN SITEMAP GENERATION COMPLETE');
  console.log('═══════════════════════════════════════');
  console.log('');
  console.log('Generated files:');
  console.log(`  • public/sitemap.xml (index, ${sitemapList.length} sitemaps)`);
  console.log(`  • public/sitemap-offers.xml (${offerEntries.length} URLs)`);
  console.log(`  • public/sitemap-static.xml (${staticEntries.length} URLs)`);
  if (blogEntries.length > 0) {
    console.log(`  • public/sitemap-blog.xml (${blogEntries.length} URLs)`);
  }
  console.log('');
  console.log('NOT generated (by design):');
  console.log('  • NO noindex sitemap');
  console.log('  • NO /whop/ URLs');
  console.log('  • NO chunked sitemaps');
  console.log('');
}

main()
  .catch((e) => {
    console.error('\n❌ SITEMAP GENERATION FAILED:', e.message);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
