import fs from 'node:fs/promises';
import { prisma } from '../src/lib/prisma';

// Emergency skip for production builds
if (process.env.SKIP_SEO_BUILD === '1' || process.env.SKIP_SEO_BUILD === 'true') {
  console.log('[seo] skipping build');
  process.exit(0);
}

process.on('unhandledRejection', e => { console.error('[seo] unhandled', e); process.exit(1); });

// No-locale path builder (canonical route is /offer/)
const pathFor = (slug: string) => `/offer/${slug}`;

async function hasColumn(table: string, column: string) {
  const rows = await prisma.$queryRaw<Array<{ exists: boolean }>>`
    SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${table} AND column_name = ${column}
    ) AS "exists"
  `;
  return rows[0]?.exists === true;
}

async function main() {
  console.log('🔨 Building SEO indexes...');
  
  await prisma.$connect();
  
  // Debug logging for preview deployment troubleshooting
  console.log('[seo-gen] host', new URL(process.env.DATABASE_URL!).host);
  console.log('[seo-gen] ayecon', await prisma.deal.findUnique({ 
    where: { slug: 'ayecon-academy-1:1-mentorship' }, 
    select: { slug: true, retirement: true, indexingStatus: true, retired: true } 
  }));
  
  try {
    // Check if we have the new retirement column or need to fall back to legacy
    const hasRetirement = await hasColumn('Whop', 'retirement');
    const hasIndexingStatus = await hasColumn('Whop', 'indexingStatus');
    
    console.log(`📊 Schema check: retirement=${hasRetirement}, indexingStatus=${hasIndexingStatus}`);
    
    // Get retired paths with fallback to legacy column
    const retired = hasRetirement
      ? await prisma.deal.findMany({ where: { retirement: 'GONE' }, select: { slug: true } })
      : await prisma.deal.findMany({ where: { retired: true }, select: { slug: true } });

    // Get noindex paths with fallback to legacy column
    const noindex = hasRetirement && hasIndexingStatus
      ? await prisma.deal.findMany({ where: { indexingStatus: 'NOINDEX', retirement: 'NONE' }, select: { slug: true } })
      : await prisma.deal.findMany({ where: { indexingStatus: 'NOINDEX' }, select: { slug: true } });

    const retiredPaths = retired.map(r => pathFor(r.slug));
    const noindexPaths = noindex.map(r => pathFor(r.slug));

    const code = `// AUTO-GENERATED by scripts/build-seo-indexes.ts
// Do not edit manually
export const RETIRED_PATHS = new Set<string>(${JSON.stringify(retiredPaths, null, 2)});
export const NOINDEX_PATHS = new Set<string>(${JSON.stringify(noindexPaths, null, 2)});
`;

    await fs.mkdir('./src/app/_generated', { recursive: true });
    await fs.writeFile('./src/app/_generated/seo-indexes.ts', code);
    
    console.log(`✅ Generated SEO indexes: retired=${retiredPaths.length}, noindex=${noindexPaths.length}`);
    console.log('📁 Written to: ./src/app/_generated/seo-indexes.ts');
    
  } catch (e: any) {
    console.error('[seo] query failed:', e?.code, e?.message, e?.meta);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();