import { prisma } from '../src/lib/prisma';

// Top Whop affiliates - key brand identifiers only (no generic words)
const brandSearches: Array<{brand: string, searchTerms: string[]}> = [
  { brand: 'Divine', searchTerms: ['divine'] },
  { brand: 'ParlayScience', searchTerms: ['parlayscience'] },
  { brand: 'GOAT Sports Bets', searchTerms: ['goatsportsbets', 'goatsports'] },
  { brand: 'Social Army', searchTerms: ['socialarmy'] },
  { brand: 'Wealth Group', searchTerms: ['wealthgroup'] },
  { brand: 'Beat the Books', searchTerms: ['beatthebooks'] },
  { brand: 'Scarface Trades', searchTerms: ['scarface'] },
  { brand: 'Stocks with Josh', searchTerms: ['stockswithjosh', 'swj'] },
  { brand: 'GG33 Academy', searchTerms: ['gg33'] },
  { brand: 'Ecom Degree University', searchTerms: ['ecomdegree'] },
  { brand: 'Skylit', searchTerms: ['skylit'] },
  { brand: 'Your First Dollar', searchTerms: ['yourfirstdollar', 'firstdollar'] },
  { brand: 'Frugal Season', searchTerms: ['frugalseason', 'frugal'] },
  { brand: 'Trust My System', searchTerms: ['trustmysystem', 'tms'] },
  { brand: 'Alertsify', searchTerms: ['alertsify'] },
  { brand: 'Hidden Society', searchTerms: ['hiddensociety'] },
  { brand: 'DEAL SOLDIER', searchTerms: ['dealsoldier'] },
  { brand: 'Potion Alpha', searchTerms: ['potion'] },
  { brand: 'MediaLabs', searchTerms: ['medialabs'] },
  { brand: 'GFNF', searchTerms: ['gfnf'] },
  { brand: 'Kaizen', searchTerms: ['kaizen'] },
  { brand: 'Hold My Hand Wholesale', searchTerms: ['holdmyhand'] },
  { brand: 'Juiced Bets', searchTerms: ['juicedbets', 'juiced'] },
  { brand: 'Profit Lounge', searchTerms: ['profitlounge'] },
  { brand: 'Trophies Sports Picks', searchTerms: ['trophies'] },
  { brand: '6-Figure Creator', searchTerms: ['6figurecreator', '6figure'] },
  { brand: 'Team Bull Trading', searchTerms: ['teambull'] },
  { brand: 'Media Metas', searchTerms: ['mediametas'] },
  { brand: 'eMoney', searchTerms: ['emoney'] },
  { brand: 'HobbyHangout', searchTerms: ['hobbyhangout'] },
  { brand: 'Stock Talk Insiders', searchTerms: ['stocktalkinsiders', 'stocktalk'] },
  { brand: 'Big Gains Club', searchTerms: ['biggains'] },
  { brand: 'Spy Essentials', searchTerms: ['spyessentials'] },
  { brand: 'The Haven', searchTerms: ['thehaven'] },
  { brand: 'BetRecaps', searchTerms: ['betrecaps'] },
  { brand: 'PropFellas', searchTerms: ['propfellas'] },
  { brand: 'RT Picks', searchTerms: ['rtpicks'] },
  { brand: 'Mogul Stock Group', searchTerms: ['mogulstock', 'mogul'] },
  { brand: 'Stock Hours', searchTerms: ['stockhours'] },
  { brand: 'Exclusive Analytics', searchTerms: ['exclusiveanalytics'] },
  { brand: 'Owls Options Traders', searchTerms: ['owlsoptions', 'owls'] },
  { brand: 'Stock Levels University', searchTerms: ['stocklevels'] },
  { brand: 'Black Tie Analytics', searchTerms: ['blacktie'] },
  { brand: 'Viral Vision', searchTerms: ['viralvision'] },
  { brand: 'the zesty chefs', searchTerms: ['zestychefs', 'zesty'] },
  { brand: 'Honey Drip Network', searchTerms: ['honeydrip'] },
  { brand: 'Ecom Tools', searchTerms: ['ecomtools'] },
  { brand: 'Stellar AIO', searchTerms: ['stellaraio', 'stellar'] },
  { brand: 'SPY BANK', searchTerms: ['spybank'] },
  { brand: 'TradeProElite', searchTerms: ['tradeproelite', 'tradepro'] },
  { brand: 'Push Platform', searchTerms: ['pushplatform'] },
  { brand: 'Ambassador Academy', searchTerms: ['ambassadoracademy', 'ambassador'] },
  { brand: 'Larrys Lounge', searchTerms: ['larryslounge', 'larrys'] },
  { brand: 'KingCapSports', searchTerms: ['kingcapsports', 'kingcap'] },
  { brand: 'Cash Flow University', searchTerms: ['cashflowuniversity', 'cashflow'] },
  { brand: 'The Sweepers', searchTerms: ['thesweepers', 'sweepers'] },
  { brand: 'AdRevival', searchTerms: ['adrevival'] },
  { brand: 'SwipeSignals', searchTerms: ['swipesignals'] },
  { brand: 'CourtSide Locks', searchTerms: ['courtsidelocks', 'courtside'] },
  { brand: 'Trade With Insight', searchTerms: ['tradewithinsight'] },
  { brand: 'Shocked', searchTerms: ['shocked'] },
  { brand: 'Scalboost', searchTerms: ['scalboost'] },
  { brand: 'Crystal Academy', searchTerms: ['crystalacademy'] },
  { brand: 'EzTrades', searchTerms: ['eztrades'] },
  { brand: 'FU Money Club', searchTerms: ['fumoney'] },
  { brand: 'Official Picks', searchTerms: ['officialpicks'] },
  { brand: 'Lunch Money', searchTerms: ['lunchmoney'] },
  { brand: 'Miles High Club', searchTerms: ['mileshigh'] },
  { brand: 'SOUSA VIP', searchTerms: ['sousavip', 'sousa'] },
  { brand: 'Bandars Bounties', searchTerms: ['bandars'] },
  { brand: 'FLIPFLUENCE', searchTerms: ['flipfluence'] },
  { brand: 'PlayBit', searchTerms: ['playbit'] },
  { brand: 'Options Insider', searchTerms: ['optionsinsider'] },
  { brand: 'Polar Chefs', searchTerms: ['polarchefs'] },
  { brand: 'GLO Sports', searchTerms: ['glosports', 'glo'] },
  { brand: 'Cook the Books', searchTerms: ['cookthebooks'] },
  { brand: 'VALUE Spy Crew', searchTerms: ['valuespycrew', 'valuespy'] },
  { brand: 'PokeNotify', searchTerms: ['pokenotify'] },
  { brand: 'The Options Cartel', searchTerms: ['optionscartel'] },
  { brand: 'Silently', searchTerms: ['silently'] },
  { brand: 'RakeTrades', searchTerms: ['raketrades'] },
  { brand: 'TopTierBetz', searchTerms: ['toptierbetz'] },
  { brand: 'Traffic Hackers', searchTerms: ['traffichackers'] },
  { brand: 'Her Last Call Academy', searchTerms: ['herlastcall'] },
  { brand: 'Equinox Traders', searchTerms: ['equinox'] },
  { brand: 'The Traveling Trader', searchTerms: ['travelingtrader'] },
  { brand: 'Rise Now', searchTerms: ['risenow'] },
  { brand: 'Sourced Betting', searchTerms: ['sourcedbetting'] },
  { brand: 'Pokecop', searchTerms: ['pokecop'] },
  { brand: 'ecomtalent', searchTerms: ['ecomtalent'] },
  { brand: 'New Age Trading', searchTerms: ['newagetrading'] },
  { brand: 'SICKBOYTRADES', searchTerms: ['sickboytrades', 'sickboy'] },
  { brand: 'Sindbad', searchTerms: ['sindbad'] },
  { brand: 'Bravo Six Picks', searchTerms: ['bravosix'] },
  { brand: 'Bookie Bandit', searchTerms: ['bookiebandit'] },
  { brand: 'The Agent Accelerator', searchTerms: ['agentaccelerator'] },
  { brand: 'Full Port University', searchTerms: ['fullport'] },
  { brand: 'Book of Alpha', searchTerms: ['bookofalpha'] },
  { brand: 'The Buy Box', searchTerms: ['thebuybox', 'buybox'] },
  { brand: 'COMMERCIVE', searchTerms: ['commercive'] },
  { brand: 'DataWise', searchTerms: ['datawise'] },
  { brand: 'ToolSuite', searchTerms: ['toolsuite'] },
  { brand: 'Zzz Money Club', searchTerms: ['zzzmoney'] },
  { brand: 'Tailored Trades', searchTerms: ['tailoredtrades'] },
  { brand: 'RisingPhoenixTrades', searchTerms: ['risingphoenix'] },
  { brand: 'SAR Trading', searchTerms: ['sartrading'] },
  { brand: 'Ecom Paradise', searchTerms: ['ecomparadise'] },
  { brand: 'Ticket Broker U', searchTerms: ['ticketbroker'] },
  { brand: 'Team2Trading', searchTerms: ['team2trading'] },
  { brand: 'Dodgys Dungeon', searchTerms: ['dodgys', 'dodgy'] },
  { brand: 'Live Academy', searchTerms: ['liveacademy'] },
  { brand: 'Rippy Club', searchTerms: ['rippyclub', 'rippy'] },
  { brand: 'Bettor Odds', searchTerms: ['bettorodds'] },
  { brand: '1of1DFS', searchTerms: ['1of1dfs'] },
  { brand: 'Bet Bettor', searchTerms: ['betbettor'] },
  { brand: 'MC Sports Analytics', searchTerms: ['mcsports'] },
  { brand: 'Tailed EnterPrize', searchTerms: ['tailedenterprise'] },
  { brand: 'Resellers Paradise', searchTerms: ['resellersparadise'] },
  { brand: 'Only Bands Money', searchTerms: ['onlybands'] },
  { brand: '50x Club', searchTerms: ['50xclub', '50x'] },
  { brand: 'House Of Resell', searchTerms: ['houseofresell'] },
  { brand: 'OasisAlerts', searchTerms: ['oasisalerts'] },
  { brand: 'DCRYPT', searchTerms: ['dcrypt'] },
  { brand: 'CHEESELOCKS', searchTerms: ['cheeselocks'] },
  { brand: 'Whale Room', searchTerms: ['whaleroom'] },
  { brand: 'BH Insights', searchTerms: ['bhinsights'] },
  { brand: 'Tickio', searchTerms: ['tickio'] },
  { brand: 'The Yard', searchTerms: ['theyard'] },
  { brand: 'Poke Signals', searchTerms: ['pokesignals'] },
  { brand: 'Sniper Trades', searchTerms: ['snipertrades'] },
  { brand: 'Creator Syndicate', searchTerms: ['creatorsyndicate'] },
  { brand: 'Zeto Picks', searchTerms: ['zetopicks'] },
  { brand: 'SnewJ Props', searchTerms: ['snewj'] },
  { brand: 'Aurora Trading', searchTerms: ['auroratrading'] },
  { brand: 'The Peachy Investor', searchTerms: ['peachyinvestor'] },
  { brand: 'Shiny Town', searchTerms: ['shinytown'] },
  { brand: 'Ghostsportzpickz', searchTerms: ['ghostsportz'] },
  { brand: 'Futdreamss', searchTerms: ['futdreamss'] },
  { brand: 'Content Academy', searchTerms: ['contentacademy'] },
  { brand: 'The Market Lens', searchTerms: ['marketlens'] },
  { brand: 'Degen Tavern', searchTerms: ['degentavern'] },
  { brand: 'Uncharted Territory', searchTerms: ['unchartedterritory'] },
  { brand: 'KAPITALAUFBAU', searchTerms: ['kapitalaufbau'] },
  { brand: 'Proxcop', searchTerms: ['proxcop'] },
  { brand: 'Top Floor Trading', searchTerms: ['topfloor'] },
  { brand: 'PowerTrades', searchTerms: ['powertrades'] },
  { brand: 'DemonTrading', searchTerms: ['demontrading'] },
  { brand: 'AdexTrades', searchTerms: ['adextrades'] },
  { brand: 'Top Tier Signals', searchTerms: ['toptiersignals'] },
  { brand: 'Topblast', searchTerms: ['topblast'] },
  { brand: 'Your Best Bet', searchTerms: ['yourbestbet'] },
  { brand: 'Paragn Network', searchTerms: ['paragn'] },
  { brand: 'Locker Room', searchTerms: ['lockerroom'] },
  { brand: 'Trade With Titans', searchTerms: ['tradewithtitans'] },
  { brand: 'Front Runners', searchTerms: ['frontrunners'] },
  { brand: 'School of gods', searchTerms: ['schoolofgods'] },
  { brand: 'Dr Profit', searchTerms: ['drprofit'] },
  { brand: 'Chroma Trading', searchTerms: ['chromatrading', 'chroma'] },
  { brand: 'Fidel Cache Flow', searchTerms: ['fidelcache'] },
  { brand: 'Tuscanyrose', searchTerms: ['tuscanyrose'] },
  { brand: 'Promoguy', searchTerms: ['promoguy'] },
  { brand: 'Market Fluidity', searchTerms: ['marketfluidity'] },
  { brand: 'Social Club Academy', searchTerms: ['socialclub'] },
  { brand: 'Arbitrage Ops', searchTerms: ['arbitrageops'] },
  { brand: 'Lowkey Discord', searchTerms: ['lowkey'] },
  { brand: 'Trade By Design', searchTerms: ['tradebydesign'] },
  { brand: 'Dropship Journey', searchTerms: ['dropshipjourney'] },
  { brand: 'PB Premium', searchTerms: ['pbpremium'] },
  { brand: 'PJ Trades', searchTerms: ['pjtrades'] },
  { brand: 'KC Trades', searchTerms: ['kctrades'] },
  { brand: 'Bread and Butter', searchTerms: ['breadandbutter'] },
  { brand: 'OddsJuice', searchTerms: ['oddsjuice'] },
  { brand: 'LIMITLES', searchTerms: ['limitles', 'limitless'] },
  { brand: 'LuxuryPaid', searchTerms: ['luxurypaid'] },
  { brand: 'Certified Crypto', searchTerms: ['certifiedcrypto'] },
  { brand: 'YAUPICKS', searchTerms: ['yaupicks'] },
  { brand: 'Tikey Tickets', searchTerms: ['tikeytickets', 'tikey'] },
  { brand: 'MTMVERSE', searchTerms: ['mtmverse'] },
  { brand: 'Endurance', searchTerms: ['endurance'] },
  { brand: 'DREANZ', searchTerms: ['dreanz'] },
  { brand: 'SharpMoney', searchTerms: ['sharpmoney'] },
  { brand: 'HiddenAIO', searchTerms: ['hiddenaio'] },
  { brand: 'Chart Hackers', searchTerms: ['charthackers'] },
  { brand: 'Trade Assist', searchTerms: ['tradeassist'] },
  { brand: 'Kenan Grace', searchTerms: ['kenangrace'] },
  { brand: 'OFM Empire', searchTerms: ['ofmempire', 'ofm'] },
  { brand: 'ABA100X', searchTerms: ['aba100x'] },
  { brand: 'Toodegrees', searchTerms: ['toodegrees'] },
  { brand: 'House of Stimms', searchTerms: ['houseofstimms', 'stimms'] },
  { brand: 'SuperLuckeee', searchTerms: ['superluckeee'] },
  { brand: 'Viral Bricks', searchTerms: ['viralbricks'] },
  { brand: 'The Hustle Club', searchTerms: ['hustleclub'] },
  { brand: 'The Wholesale Atlas', searchTerms: ['wholesaleatlas'] },
  { brand: 'GG33 University', searchTerms: ['gg33'] },
  { brand: 'Akari', searchTerms: ['akari'] },
  { brand: 'TikTok Money Maker', searchTerms: ['tiktokmoneymaker'] },
  { brand: 'The Mail Room', searchTerms: ['mailroom'] },
  { brand: 'Lions Den', searchTerms: ['lionsden'] },
  { brand: 'GOATIFY', searchTerms: ['goatify'] },
  { brand: 'Empire Sports Betting', searchTerms: ['empiresports'] },
  { brand: 'Link Up Community', searchTerms: ['linkup'] },
  { brand: 'Jdub Trades', searchTerms: ['jdub'] },
  { brand: 'Divine Degen', searchTerms: ['divinedegen'] },
  { brand: 'NextWave Indicators', searchTerms: ['nextwave'] },
  { brand: 'Traders Blueprint', searchTerms: ['tradersblueprint'] },
  { brand: 'Skyridge', searchTerms: ['skyridge'] },
  { brand: 'DispurGen', searchTerms: ['dispurgen'] },
  { brand: 'MONETIZE', searchTerms: ['monetize'] },
  { brand: '247 Terminal', searchTerms: ['247terminal'] },
  { brand: 'Huracan Trading', searchTerms: ['huracan'] },
  { brand: 'Startup Preneurs', searchTerms: ['startuppreneurs'] },
  { brand: 'AutoFlipped', searchTerms: ['autoflipped'] },
  { brand: 'Bet Labs Sports', searchTerms: ['betlabs'] },
  { brand: 'AMNotify', searchTerms: ['amnotify'] },
  { brand: 'Phantom Checker', searchTerms: ['phantomchecker'] },
  { brand: 'Tempo Trades', searchTerms: ['tempotrades'] },
  { brand: 'TTS Insiders', searchTerms: ['ttsinsiders'] },
  { brand: 'Derivatives Trading', searchTerms: ['derivatives'] },
  { brand: 'Moon Trades', searchTerms: ['moontrades'] },
  { brand: 'Asozial', searchTerms: ['asozial'] },
  { brand: 'PeloSwing', searchTerms: ['peloswing'] },
  { brand: 'DealHawk', searchTerms: ['dealhawk'] },
  { brand: 'Levs Locks', searchTerms: ['levslocks'] },
  { brand: 'Jonahs Stocks', searchTerms: ['jonahs'] },
  { brand: 'Shiftly', searchTerms: ['shiftly'] },
  { brand: 'Kckd Notify', searchTerms: ['kckd'] },
  { brand: 'IG Growth Tool', searchTerms: ['iggrowth'] },
  { brand: 'WW Global Alliance', searchTerms: ['wwglobal'] },
  { brand: 'LiveCops', searchTerms: ['livecops'] },
  { brand: 'WEALTH HUB', searchTerms: ['wealthhub'] },
  { brand: 'Kaikicks', searchTerms: ['kaikicks'] },
  { brand: 'Poke Pandemonium', searchTerms: ['pokepandemonium'] },
  { brand: 'Paper Gains', searchTerms: ['papergains'] },
  { brand: 'All In Abe', searchTerms: ['allinabe'] },
  { brand: 'Props Lab', searchTerms: ['propslab'] },
  { brand: 'Trade Craft Tools', searchTerms: ['tradecraft'] },
  { brand: 'Vulture', searchTerms: ['vulture'] },
  { brand: 'Max Options Trading', searchTerms: ['maxoptions'] },
  { brand: 'De Wolf van Washington', searchTerms: ['dewolf'] },
  { brand: 'Crypto Archie', searchTerms: ['cryptoarchie'] },
  { brand: 'Tiktok Titans', searchTerms: ['tiktoktitans'] },
  { brand: 'Bands VIP', searchTerms: ['bandsvip'] },
  { brand: '28 Club', searchTerms: ['28club'] },
  { brand: 'The Lab', searchTerms: ['thelab'] },
  { brand: 'House of Profits', searchTerms: ['houseofprofits'] },
  { brand: 'The Doc Prop', searchTerms: ['docprop'] },
  { brand: 'Momentum', searchTerms: ['momentum'] },
  { brand: 'Shadows Chefs', searchTerms: ['shadowschefs'] },
  { brand: 'The Krypto King', searchTerms: ['kryptoking'] },
  { brand: 'CB Trading', searchTerms: ['cbtrading'] },
  { brand: 'Socialbuz', searchTerms: ['socialbuz'] },
  { brand: 'Free Cash Premium', searchTerms: ['freecash'] },
  { brand: 'Printers Paradise', searchTerms: ['printersparadise'] },
  { brand: 'Impact Team', searchTerms: ['impactteam'] },
  { brand: 'Traders Wealth', searchTerms: ['traderswealth'] },
  { brand: 'The Alliance', searchTerms: ['thealliance'] },
  { brand: 'Trinity Trading', searchTerms: ['trinitytrading'] },
  { brand: 'Alpine Trading', searchTerms: ['alpinetrading'] },
  { brand: 'Zamunda', searchTerms: ['zamunda'] },
  { brand: 'LV Trades', searchTerms: ['lvtrades'] },
  { brand: 'Blastoise', searchTerms: ['blastoise'] },
  { brand: 'Platinum Trading', searchTerms: ['platinumtrading'] },
  { brand: 'STOCK KING SHARKS', searchTerms: ['stockkingsharks'] },
  { brand: 'Playbook Investment', searchTerms: ['playbookinvestment'] },
  { brand: 'GammaEdge', searchTerms: ['gammaedge'] },
  { brand: 'THE ECOM MASTERCLASS', searchTerms: ['ecommasterclass'] },
  { brand: 'NPZ Trading', searchTerms: ['npztrading'] },
  { brand: 'Savage Ecom', searchTerms: ['savageecom'] },
  { brand: 'ChilliManPicks', searchTerms: ['chilliman'] },
  { brand: '4ORTE', searchTerms: ['4orte'] },
  { brand: 'Deal Sniper', searchTerms: ['dealsniper'] },
  { brand: 'Unity Academy', searchTerms: ['unityacademy'] },
  { brand: 'Parlay Minds', searchTerms: ['parlayminds'] },
  { brand: 'Flash Fund', searchTerms: ['flashfund'] },
  { brand: 'The Syndicate', searchTerms: ['thesyndicate'] },
  { brand: 'The Family', searchTerms: ['thefamily'] },
  { brand: 'Baron Trading', searchTerms: ['barontrading'] },
  { brand: 'Earnit Media', searchTerms: ['earnitmedia'] },
  { brand: 'MoneyBoys Stock', searchTerms: ['moneyboys'] },
  { brand: 'Black Sheep Culture', searchTerms: ['blacksheep'] },
  { brand: 'Assassin Stocks', searchTerms: ['assassinstocks'] },
  { brand: 'Ascent Repricer', searchTerms: ['ascentrepricer', 'ascent'] },
  { brand: 'Traders Compound', searchTerms: ['traderscompound'] },
  { brand: 'Boka Trading', searchTerms: ['bokatrading', 'boka'] },
  { brand: 'Exposcale', searchTerms: ['exposcale'] },
  { brand: 'SPY Day Trading', searchTerms: ['spydaytrading'] },
  { brand: 'Clutch Investments', searchTerms: ['clutchinvestments'] },
  { brand: 'Gargantua AIO', searchTerms: ['gargantua'] },
  { brand: '502SLIPS', searchTerms: ['502slips'] },
  { brand: 'The Fractal Exchange', searchTerms: ['fractalexchange'] },
  { brand: 'Degen VIP', searchTerms: ['degenvip'] },
  { brand: 'Nautilus Deals', searchTerms: ['nautilus'] },
  { brand: 'Enrich Trades', searchTerms: ['enrichtrades'] },
  { brand: 'SolarTools', searchTerms: ['solartools'] },
  { brand: 'Megoda', searchTerms: ['megoda'] },
  { brand: 'PUSHING PROFIT', searchTerms: ['pushingprofit'] },
  { brand: 'The Champagne Room', searchTerms: ['champagneroom'] },
  { brand: 'FlipAlert', searchTerms: ['flipalert'] },
  { brand: 'Edge Zone', searchTerms: ['edgezone'] },
  { brand: 'FirstStepTrading', searchTerms: ['firststep'] },
  { brand: 'NotifyFrance', searchTerms: ['notifyfrance'] },
  { brand: 'Arts Crypto Circle', searchTerms: ['artscrypto'] },
  { brand: 'Monster Bet', searchTerms: ['monsterbet'] },
  { brand: 'TookThatTradingGroup', searchTerms: ['tookthat'] },
  { brand: 'InTheCircle', searchTerms: ['inthecircle'] },
  { brand: 'UnknownCollect', searchTerms: ['unknowncollect'] },
  { brand: 'bolo group', searchTerms: ['bolo'] },
  { brand: 'Trade Manager', searchTerms: ['trademanager'] },
  { brand: 'GabesAlerts', searchTerms: ['gabesalerts'] },
  { brand: 'Resale Radar', searchTerms: ['resaleradar'] },
  { brand: 'SneakersyncLabs', searchTerms: ['sneakersync'] },
  { brand: 'VenomCooks', searchTerms: ['venomcooks'] },
  { brand: 'Price Hacking', searchTerms: ['pricehacking'] },
  { brand: 'Botos Trading', searchTerms: ['botos'] },
  { brand: 'Quantum Algo', searchTerms: ['quantumalgo'] },
  { brand: 'PaysToWait', searchTerms: ['paystowait'] },
  { brand: '242 Just Picks', searchTerms: ['242'] },
  { brand: 'Cakes Bakes', searchTerms: ['cakesbakes'] },
  { brand: 'Gambling Gurus', searchTerms: ['gamblinggurus'] },
  { brand: 'SelfMade Society', searchTerms: ['selfmade'] },
  { brand: 'Elevate Community', searchTerms: ['elevate'] },
  { brand: 'Select Trading', searchTerms: ['selecttrading'] },
  { brand: 'PokeFreeze Notify', searchTerms: ['pokefreeze'] },
  { brand: 'ZTH Training', searchTerms: ['zth'] },
  { brand: 'NextGen Publishers', searchTerms: ['nextgen'] },
  { brand: 'ndotdiab', searchTerms: ['ndotdiab'] },
  { brand: 'Boss Up Academy', searchTerms: ['bossup'] },
  { brand: '444 Capital Club', searchTerms: ['444'] },
  { brand: 'NikeShoeBot', searchTerms: ['nikeshoebot'] },
  { brand: 'Insiderz', searchTerms: ['insiderz'] },
  { brand: 'Creator Cashflow', searchTerms: ['creatorcashflow'] },
  { brand: 'FBA ACADEMY', searchTerms: ['fbaacademy'] },
  { brand: 'Straight Shooters', searchTerms: ['straightshooters'] },
  { brand: 'Team 100K Trading', searchTerms: ['team100k'] },
  { brand: 'Gains Gears', searchTerms: ['gainsgears'] },
  { brand: 'Shadow Flips', searchTerms: ['shadowflips'] },
  { brand: 'Voss Trading', searchTerms: ['vosstrading'] },
  { brand: 'No Sweat Bets', searchTerms: ['nosweat'] },
  { brand: 'Card Followers', searchTerms: ['cardfollowers'] },
  { brand: 'Meme Mafia', searchTerms: ['mememafia'] },
  { brand: 'MoonBoys Crypto', searchTerms: ['moonboys'] },
  { brand: 'Pay2PlayUniversity', searchTerms: ['pay2play'] },
  { brand: 'Dopamine', searchTerms: ['dopamine'] },
  { brand: 'Propbet Mafia', searchTerms: ['propbetmafia', 'propbet'] },
  { brand: 'Spitfire Traders', searchTerms: ['spitfire'] },
  { brand: 'TheWave', searchTerms: ['thewave'] },
  { brand: 'Profit Insider', searchTerms: ['profitinsider'] },
  { brand: 'SharpTank', searchTerms: ['sharptank'] },
  { brand: 'Uproas', searchTerms: ['uproas'] },
  { brand: 'Fyndit', searchTerms: ['fyndit'] },
  { brand: 'PokeFinder', searchTerms: ['pokefinder'] },
  { brand: 'Profit Pioneers', searchTerms: ['profitpioneers'] },
  { brand: 'The Sweatshop', searchTerms: ['sweatshop'] },
  { brand: 'MAI Bets', searchTerms: ['maibets'] },
  { brand: 'Viral Flow', searchTerms: ['viralflow'] },
  { brand: 'League Mastery', searchTerms: ['leaguemastery'] },
  { brand: 'Trading Options Academy', searchTerms: ['tradingoptionsacademy'] },
];

async function findMatches() {
  const dealsWithPromos = await prisma.deal.findMany({
    where: {
      PromoCode: { some: {} },
      NOT: { retirement: 'GONE' }
    },
    select: {
      name: true,
      slug: true,
      _count: { select: { PromoCode: true } }
    }
  });

  console.log(`Found ${dealsWithPromos.length} deals with promo codes\n`);
  console.log('=== MATCHES ===\n');

  const matches: Array<{brand: string, name: string, slug: string, promos: number}> = [];

  for (const { brand, searchTerms } of brandSearches) {
    for (const deal of dealsWithPromos) {
      const dealNameNorm = deal.name.toLowerCase().replace(/[^a-z0-9]/g, '');
      const dealSlugNorm = deal.slug.toLowerCase().replace(/[^a-z0-9]/g, '');

      for (const term of searchTerms) {
        if (dealNameNorm.includes(term) || dealSlugNorm.includes(term)) {
          matches.push({ brand, name: deal.name, slug: deal.slug, promos: deal._count.PromoCode });
          break;
        }
      }
    }
  }

  // Dedupe by slug
  const seen = new Set<string>();
  const unique = matches.filter(m => {
    if (seen.has(m.slug)) return false;
    seen.add(m.slug);
    return true;
  });

  unique.sort((a, b) => a.brand.localeCompare(b.brand));

  let count = 1;
  for (const m of unique) {
    console.log(`${count}. "${m.brand}" → ${m.name} (${m.slug})`);
    count++;
  }

  console.log(`\n=== TOTAL: ${unique.length} ===`);
}

findMatches().catch(console.error).finally(() => prisma.$disconnect());
